name: CI TK-storePhp
name: Vérification PHP

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  php-lint:
    name: Analyse de base PHP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🔧 Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: ✅ Vérifier la syntaxe PHP
        run: |
          find . -type f -name "*.php" -exec php -l {} \;
